name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main   # change if using another branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "prince187p0kharna@gmail.com"
          git config --global user.name "github-actions"

          git clone https://user:$HF_TOKEN@huggingface.co/spaces/prinzep/human-ai-optimizer hf-space
          rsync -av --exclude '.git' ./ hf-space/

          cd hf-space
          git add .
          git commit -m "Update from GitHub" || echo "No changes to commit"
          git push